selenium: '3.141.0'
firefox: '63.0'
firefox_driver: '0.23.0'
chromedriver: '2.43'
iedriver: '3.3.0'
iedriver_major: '3.3'
edgedriver: '14393'
edgedriver_eula: 'https://az813057.vo.msecnd.net/eulas/webdriver-eula.pdf'
edgedriver_url: 'https://download.microsoft.com/download/3/2/D/32D3E464-F2EF-490F-841B-05D53C848D15/MicrosoftWebDriver.exe'
